"""initial migration for air quality table

Revision ID: 3008deefa98c
Revises: 
Create Date: 2024-03-19 11:06:21.970355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3008deefa98c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('elevation', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_quality_data'), 'air_quality', ['data'], unique=False)
    op.create_index(op.f('ix_air_quality_elevation'), 'air_quality', ['elevation'], unique=False)
    op.create_index(op.f('ix_air_quality_id'), 'air_quality', ['id'], unique=False)
    op.create_index(op.f('ix_air_quality_latitude'), 'air_quality', ['latitude'], unique=False)
    op.create_index(op.f('ix_air_quality_longitude'), 'air_quality', ['longitude'], unique=False)
    op.create_index(op.f('ix_air_quality_tags'), 'air_quality', ['tags'], unique=False)
    op.create_index(op.f('ix_air_quality_type'), 'air_quality', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_air_quality_type'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_tags'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_longitude'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_latitude'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_id'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_elevation'), table_name='air_quality')
    op.drop_index(op.f('ix_air_quality_data'), table_name='air_quality')
    op.drop_table('air_quality')
    # ### end Alembic commands ###
