"""added column created_at

Revision ID: adc19885ce61
Revises: 7214d33d9feb
Create Date: 2024-03-19 21:55:01.323138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc19885ce61'
down_revision: Union[str, None] = '7214d33d9feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_quality', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_quality', 'created_at')
    # ### end Alembic commands ###
